### PR TITLE
My model train result

### PR DESCRIPTION
**Pull request by lzk2211**
I have train this experiment used my network oneD_lw_ResNet.

### CODE REVIEW

**Comment by xyanchen** [comment]
Hi lzk2211,

Please do not directly add your modifications to the original repository as this repository is an opensource public repository. You could folk the repository and perform modifications witin it.

Thanks for your understanding and I will close the pull request.

Regards,
xyanchen

**Comment by lzk2211** [comment]
Sorry, I'm learning how to use GitHub by accident, please forgive me!








刘振坤

北京邮电大学/研博生/信息与通信工程学院



北京




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Dec 4, 2024 09:29 PM
To: ***@***.***&gt;; 
Cc: &nbsp;"Zhenkun ***@***.***&gt;; "State ***@***.***&gt;; 
Subject: &nbsp;Re: [xyanchen/WiFi-CSI-Sensing-Benchmark] My model train result (PR #21)

&nbsp;



 
Hi lzk2211,
 
Please do not directly add your modifications to the original repository as this repository is an opensource public repository. You could folk the repository and perform modifications witin it.
 
Thanks for your understanding and I will close the pull request.
 
Regards,
 xyanchen

**Comment by lzk2211** [comment]
Hi I would like to remove this pull request completely, your project name keeps appearing in my repository and I don't know how to find the relevant key, could you help me remove this pull go request, thanks a million!

**Comment by lzk2211** [comment]
Hi I would like to remove this pull request completely, your project name keeps appearing in my repository and I don't know how to find the relevant key, could you help me remove this pull go request, thanks a million!

**Pull request closed without merging**
